# Java Makefile version 1.0.0 Nov-19-2022 Aaron Santana Valdelomar 

#java compiler
JC = javac 


# Directoties 

BIN_PATH = bin
OBJ_PATH = build
SRC_PATH = src
MAIN_FILE = Game.java 

# commands 

debug: $(JC) $(MAIN_FILE) -d $(OBJ_PATH)
